name: refreshed_cli
version: 1.0.0-pre.1
homepage: https://github.com/Aniketkhote/refreshed_cli
description: Official CLI for Refreshed framework to build Flutter Applications easily

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ansicolor: "^2.0.2"
  collection: "^1.18.0"
  dart_style: "^2.3.6"
  dcli: "^4.0.1-alpha.8"
  http: "^1.2.1"
  intl: ">=0.18.1 <=1.0.0"
  meta: "^1.12.0"
  path: ">=1.8.3 <=2.0.0"
  process_run: "^0.14.2"
  pubspec: "^2.3.0"
  recase: "^4.1.0"
  version: "^3.0.2"
  yaml: "^3.1.2"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

executables:
  get: refreshed
