name: refreshed_cli
version: 1.1.2
homepage: https://github.com/Aniketkhote/refreshed_cli
description: Official CLI for Refreshed framework to build Flutter Applications easily

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  ansicolor: "^2.0.2"
  collection: "^1.19.0"
  dart_style: "^3.0.0"
  dcli: "^6.0.5"
  http: "^1.2.2"
  intl: ">=0.19.0 <=1.0.0"
  meta: "^1.15.0"
  path: ">=1.8.3 <=2.0.0"
  process_run: "^1.1.0"
  pubspec: "^2.3.0"
  recase: "^4.1.0"
  version: "^3.0.2"
  yaml: "^3.1.2"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

executables:
  get: refreshed
